### PR TITLE
questionable fix that needs some thinking

### PR DESCRIPTION
**Pull request by matentzn**
The problem with computing CURIEs from IRIs is actually more fundamentally flawed in OLS then I assumed; It basically assumes that somehow, you can derive the Curie by splitting the uri fragment at the underscore:

(from [ols](https://github.com/EBISPOT/OLS/blob/7f63b84258d13c4acfebe641adca3ad972bf7ec0/ontology-tools/src/main/java/uk/ac/ebi/spot/ols/loader/AbstractOWLOntologyLoader.java#L1124-L1134)) 

```
private static final Pattern oboIdFragmentPattern = Pattern.compile("(^([A-Za-z0-9_]*)_([A-Za-z0-9]*)$)");
```

If you have a fragment like `GCS_hello_world`, this split will yield a curie like `GCS_hello:world` Now we could change the syntax matcher to:

```
private static final Pattern oboIdFragmentPattern = Pattern.compile("(^([A-Za-z0-9]*)_([A-Za-z0-9_]*)$)");
```

Essentially moving the `_` to the second group. This would work for my case, but right now, I have no idea what other consequences that would have. Since OLS is the more important of the two services, maybe we can just use this here in the meantime, which essentially uses the declared `base_uri` if present, in concert with the preferred prefix, to construct a curie. Its kinda ok. Not sure if I thought of all consequences. One problem is when you have multiple base_uris; in that case the mapping between CURIE syntax and IRI becomes ambuiguous..

### CODE REVIEW

**Comment by udp** [comment]
> I think the correct solution is to maintain EBI curie_map, or, add a configuration app that provide curie_maps on a ontology_by_ontology basis..

Yes, I think moving the curie map into the config would be the correct approach. @henrietteharmse, what do you think?

**Comment by henrietteharmse** [comment]
> > I think the correct solution is to maintain EBI curie_map, or, add a configuration app that provide curie_maps on a ontology_by_ontology basis..
> 
> Yes, I think moving the curie map into the config would be the correct approach. @henrietteharmse, what do you think?

What we have at the moment is brittle at best. Hence, I am very much in favour of the curie map idea. Having a CURIE map config can work. Did you think of sharing the config between OxO/OLS/Zooma(?) or each having a separate config?

**Comment by matentzn** [comment]
I think we should start thinking about sharing configuration between these apps; maybe to start with simply a location we can dump some configuration? EBISPOT/config? And agree that all configuration from now on should be in JSON. I would say that something like a curie_map really is a very general thing that we should share across applications..

**Comment by henrietteharmse** [comment]
To distinguish from other SPOT related dev I would prefer something like EBISPOT/OntoTools/Config.

And yes please use JSON. I really will prefer if we NEVER use yaml again.

**Comment by matentzn** [comment]
Sounds great! Why dont you are @udp create a new repo, like EBISPOT/ontotools-config and we continue the conversation there?

**Comment by henrietteharmse** [comment]
There is no reason why you can do it yourself.

**Comment by matentzn** [comment]
Great :P Thanks.

**Comment by matentzn** [comment]
Here it is; just didnt want to break protocol, not being SPOT officially. https://github.com/EBISPOT/ontotools-config

**Comment by udp** [comment]
Sorry @matentzn  this got closed automatically because I'm messing around with branches

Can you open it again against the `main` branch if still relevant please?

**Comment by matentzn** [comment]
Thanks for letting me know - I will do it just to keep stuff up to date.

**Comment by matentzn** [comment]
Ah, there was still a draft iopen: https://github.com/EBISPOT/OXO/pull/43/files

**Pull request closed without merging**
